name: playwright-factory

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [ '18' ]
        playwright: ['1.30.0']
    runs-on: ${{ matrix.os }}
    name: ${{matrix.os}} - Java ${{ matrix.java }} - Playwright ${{matrix.playwright}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: mvn clean test "-Dplaywright.version=${{matrix.playwright}}" --file pom.xml
